"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { ArrowRight, Check, Filter, LoaderCircle, Send } from "lucide-react";
import { useRouter } from "next/navigation";
import { useApp } from "./app-provider";
import { PageError, PageLoading } from "./page-state";
import type { JobFilter, Profile } from "@/lib/api/types";

export function OnboardingView() {
  const { api, notify } = useApp(); const router = useRouter();
  const [profile, setProfile] = useState<Profile | null>(null); const [filters, setFilters] = useState<JobFilter[]>([]);
  const [step, setStep] = useState(1); const [pending, setPending] = useState(false); const [error, setError] = useState(""); const [telegramLink, setTelegramLink] = useState("");
  const load = useCallback(async () => { try { const [nextProfile, nextFilters] = await Promise.all([api.profile(), api.filters()]); setProfile(nextProfile); setFilters(nextFilters); setStep(nextFilters.length ? 2 : 1); } catch (reason) { setError(reason instanceof Error ? reason.message : "Setup could not be loaded."); } }, [api]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);

  async function createFilter(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); const data = new FormData(event.currentTarget); const split = (name:string) => String(data.get(name) ?? "").split(",").map((value) => value.trim()).filter(Boolean); try { const created = await api.createFilter({ name:"My internship signal", role_keywords:split("roles"), location_keywords:split("locations"), terms:[String(data.get("term"))], work_mode:"any", active:true, remote_only:false }); setFilters([created]); setStep(2); } catch (reason) { notify(reason instanceof Error ? reason.message : "Filter setup failed.", "error"); } finally { setPending(false); } }
  async function saveDelivery(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!profile) return; setPending(true); const data = new FormData(event.currentTarget); try { const next = await api.updateProfile({ timezone:String(data.get("timezone")), preferred_email_time:String(data.get("email_time")), email_digest_job_limit:Number(data.get("digest_limit")), telegram_notifications_enabled:profile.telegram_chat_id !== null && data.get("telegram") === "on", email_notifications_enabled:data.get("email") === "on" }); setProfile(next); setStep(3); } catch (reason) { notify(reason instanceof Error ? reason.message : "Preferences could not be saved.", "error"); } finally { setPending(false); } }
  async function linkTelegram() { try { const result = await api.createTelegramLink(); setTelegramLink(result.deep_link); window.open(result.deep_link,"_blank","noopener,noreferrer"); } catch (reason) { notify(reason instanceof Error ? reason.message : "Telegram link failed.","error"); } }
  async function refreshTelegram() { const next = await api.profile(); setProfile(next); notify(next.telegram_chat_id ? "Telegram connected." : "Press Start in Telegram, then check again.", next.telegram_chat_id ? "success" : "error"); }

  if (error) return <PageError message={error} retry={load} />; if (!profile) return <PageLoading label="Preparing your signal" />;
  return <div className="onboarding-page"><div className="onboarding-progress" aria-label={`Setup step ${step} of 3`}>{[1,2,3].map((value)=><span className={value<=step?"active":""} key={value}>{value<step?<Check size={14}/>:value}</span>)}</div>
    {step===1&&<section className="onboarding-card"><span className="onboarding-icon"><Filter/></span><p className="page-eyebrow">Step 1 of 3</p><h1>What should we watch for?</h1><p>Start broad enough to catch opportunities. You can fine-tune this later.</p><form onSubmit={createFilter}><div className="field"><label htmlFor="onboarding-roles">Roles</label><input id="onboarding-roles" name="roles" required placeholder="software, backend, developer"/><span className="field__help">Separate a few keywords with commas.</span></div><div className="field"><label htmlFor="onboarding-locations">Locations</label><input id="onboarding-locations" name="locations" placeholder="Toronto, Canada, Remote"/></div><div className="field"><label htmlFor="onboarding-term">Internship term</label><select id="onboarding-term" name="term" defaultValue="Summer 2027">{["Fall 2026","Winter 2027","Summer 2027","Fall 2027","Winter 2028","Summer 2028","Fall 2028"].map((term)=><option key={term}>{term}</option>)}</select></div><button className="button button--primary button--full" disabled={pending}>{pending&&<LoaderCircle className="spin"/>}Create my filter<ArrowRight size={17}/></button></form></section>}
    {step===2&&<section className="onboarding-card"><span className="onboarding-icon"><Send/></span><p className="page-eyebrow">Step 2 of 3</p><h1>How should we alert you?</h1><p>Telegram sends each match immediately. Email sends one ranked daily digest.</p>{!profile.telegram_chat_id&&<div className="onboarding-connect"><button className="button button--dark" onClick={linkTelegram}>Open Telegram bot</button>{telegramLink&&<button className="button button--ghost" onClick={refreshTelegram}>I pressed Start — check</button>}</div>}<form onSubmit={saveDelivery}><label className="switch-row"><input type="checkbox" name="telegram" disabled={!profile.telegram_chat_id} defaultChecked={profile.telegram_notifications_enabled}/><span><strong>Instant Telegram alerts</strong><small>{profile.telegram_chat_id?"One message per new match":"Link Telegram first"}</small></span></label><label className="switch-row"><input type="checkbox" name="email" defaultChecked={false}/><span><strong>Daily email highlights</strong><small>Off until you explicitly enable it</small></span></label><div className="field"><label htmlFor="onboarding-email-time">Email delivery time</label><input id="onboarding-email-time" name="email_time" type="time" required defaultValue={profile.preferred_email_time.slice(0,5)}/></div><div className="field"><label htmlFor="onboarding-digest-limit">Top matches per email</label><input id="onboarding-digest-limit" name="digest_limit" type="number" min="1" max="10" required defaultValue={profile.email_digest_job_limit}/></div><div className="field"><label htmlFor="onboarding-timezone">Timezone</label><input id="onboarding-timezone" name="timezone" required defaultValue={profile.timezone}/><span className="field__help">For example America/Toronto.</span></div><button className="button button--primary button--full" disabled={pending}>Save alert preferences<ArrowRight size={17}/></button></form></section>}
    {step===3&&<section className="onboarding-card onboarding-card--complete"><span className="onboarding-icon"><Check/></span><p className="page-eyebrow">Signal ready</p><h1>Sprintern is watching.</h1><p>{filters.length} active filter is checking for new internships. New matches will appear in your feed and enabled channels.</p><button className="button button--primary" onClick={()=>router.replace("/dashboard")}>Open my dashboard<ArrowRight size={17}/></button></section>}
    {step<3&&<button className="onboarding-skip" onClick={()=>router.replace("/dashboard")}>Finish later</button>}
  </div>;
}
