"""track deterministic classification

Revision ID: a74afb2f1286
Revises: 007e0516bc00
Create Date: 2026-07-13 20:14:34.429402
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a74afb2f1286"
down_revision: str | Sequence[str] | None = "007e0516bc00"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs",
        sa.Column(
            "internship_status",
            sa.Enum(
                "unknown",
                "confirmed",
                "rejected",
                "ambiguous",
                name="internship_status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            server_default="unknown",
            nullable=False,
        ),
    )
    op.add_column("jobs", sa.Column("matcher_version", sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "matcher_version")
    op.drop_column("jobs", "internship_status")
    # ### end Alembic commands ###
