"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { ArrowRight, Check, Filter, LoaderCircle, Send } from "lucide-react";
import { useRouter } from "next/navigation";
import { useApp } from "./app-provider";
import { PageError, PageLoading } from "./page-state";
import type { JobFilter, NotificationCadence, Profile } from "@/lib/api/types";

export function OnboardingView() {
  const { api, notify } = useApp(); const router = useRouter();
  const [profile, setProfile] = useState<Profile | null>(null); const [filters, setFilters] = useState<JobFilter[]>([]);
  const [step, setStep] = useState(1); const [pending, setPending] = useState(false); const [error, setError] = useState(""); const [telegramLink, setTelegramLink] = useState("");
  const load = useCallback(async () => { try { const [nextProfile, nextFilters] = await Promise.all([api.profile(), api.filters()]); setProfile(nextProfile); setFilters(nextFilters); setStep(nextFilters.length ? 2 : 1); } catch (reason) { setError(reason instanceof Error ? reason.message : "Setup could not be loaded."); } }, [api]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);

  async function createFilter(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); const data = new FormData(event.currentTarget); const split = (name:string) => String(data.get(name) ?? "").split(",").map((value) => value.trim()).filter(Boolean); try { const created = await api.createFilter({ name:"My internship signal", role_keywords:split("roles"), location_keywords:split("locations"), terms:["Summer 2027"], work_mode:"any", active:true }); setFilters([created]); setStep(2); } catch (reason) { notify(reason instanceof Error ? reason.message : "Filter setup failed.", "error"); } finally { setPending(false); } }
  async function saveDelivery(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!profile) return; setPending(true); const data = new FormData(event.currentTarget); try { const next = await api.updateProfile({ notification_cadence:String(data.get("cadence")) as NotificationCadence, telegram_notifications_enabled:profile.telegram_chat_id !== null && data.get("telegram") === "on", email_notifications_enabled:data.get("email") === "on" }); setProfile(next); setStep(3); } catch (reason) { notify(reason instanceof Error ? reason.message : "Preferences could not be saved.", "error"); } finally { setPending(false); } }
  async function linkTelegram() { try { const result = await api.createTelegramLink(); setTelegramLink(result.deep_link); window.open(result.deep_link,"_blank","noopener,noreferrer"); } catch (reason) { notify(reason instanceof Error ? reason.message : "Telegram link failed.","error"); } }
  async function refreshTelegram() { const next = await api.profile(); setProfile(next); notify(next.telegram_chat_id ? "Telegram connected." : "Press Start in Telegram, then check again.", next.telegram_chat_id ? "success" : "error"); }

  if (error) return <PageError message={error} retry={load} />; if (!profile) return <PageLoading label="Preparing your signal" />;
  return <div className="onboarding-page"><div className="onboarding-progress" aria-label={`Setup step ${step} of 3`}>{[1,2,3].map((value)=><span className={value<=step?"active":""} key={value}>{value<step?<Check size={14}/>:value}</span>)}</div>
    {step===1&&<section className="onboarding-card"><span className="onboarding-icon"><Filter/></span><p className="page-eyebrow">Step 1 of 3</p><h1>What should we watch for?</h1><p>Start broad enough to catch opportunities. You can fine-tune this later.</p><form onSubmit={createFilter}><div className="field"><label htmlFor="onboarding-roles">Roles</label><input id="onboarding-roles" name="roles" required placeholder="software, backend, developer"/><span className="field__help">Separate a few keywords with commas.</span></div><div className="field"><label htmlFor="onboarding-locations">Locations</label><input id="onboarding-locations" name="locations" placeholder="Toronto, Canada, Remote"/></div><button className="button button--primary button--full" disabled={pending}>{pending&&<LoaderCircle className="spin"/>}Create my filter<ArrowRight size={17}/></button></form></section>}
    {step===2&&<section className="onboarding-card"><span className="onboarding-icon"><Send/></span><p className="page-eyebrow">Step 2 of 3</p><h1>How should we alert you?</h1><p>Telegram is ready immediately. Email can be enabled after Resend is configured.</p>{!profile.telegram_chat_id&&<div className="onboarding-connect"><button className="button button--dark" onClick={linkTelegram}>Open Telegram bot</button>{telegramLink&&<button className="button button--ghost" onClick={refreshTelegram}>I pressed Start — check</button>}</div>}<form onSubmit={saveDelivery}><div className="cadence-control">{(["instant","hourly","daily"] as NotificationCadence[]).map((value)=><label key={value}><input type="radio" name="cadence" value={value} defaultChecked={profile.notification_cadence===value}/><span><strong>{value}</strong><small>{value==="instant"?"Right away":`${value} digest`}</small></span></label>)}</div><label className="switch-row"><input type="checkbox" name="telegram" disabled={!profile.telegram_chat_id} defaultChecked={profile.telegram_notifications_enabled}/><span><strong>Telegram alerts</strong><small>{profile.telegram_chat_id?"Connected and available":"Link Telegram first"}</small></span></label><label className="switch-row"><input type="checkbox" name="email" defaultChecked={false}/><span><strong>Email alerts</strong><small>Leave off until Resend is configured.</small></span></label><button className="button button--primary button--full" disabled={pending}>Save alert preferences<ArrowRight size={17}/></button></form></section>}
    {step===3&&<section className="onboarding-card onboarding-card--complete"><span className="onboarding-icon"><Check/></span><p className="page-eyebrow">Signal ready</p><h1>Sprintern is watching.</h1><p>{filters.length} active filter is checking the Summer 2027 source. New matches will appear in your feed and enabled channels.</p><button className="button button--primary" onClick={()=>router.replace("/dashboard")}>Open my dashboard<ArrowRight size={17}/></button></section>}
    {step<3&&<button className="onboarding-skip" onClick={()=>router.replace("/dashboard")}>Finish later</button>}
  </div>;
}
