"""track source occurrence lifecycle

Revision ID: 007e0516bc00
Revises: 1ed3cf405b68
Create Date: 2026-07-13 20:01:13.426136
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "007e0516bc00"
down_revision: str | Sequence[str] | None = "1ed3cf405b68"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "job_sources",
        sa.Column("source_key", sa.String(length=255), server_default="legacy", nullable=False),
    )
    op.alter_column("job_sources", "source_key", server_default=None)
    op.add_column(
        "job_sources", sa.Column("occurrence", sa.Integer(), server_default="1", nullable=False)
    )
    op.add_column(
        "job_sources",
        sa.Column("missing_snapshot_count", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "job_sources", sa.Column("missing_since", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "job_sources", sa.Column("active", sa.Boolean(), server_default="true", nullable=False)
    )
    op.drop_constraint(op.f("uq_job_sources_identity"), "job_sources", type_="unique")
    op.create_unique_constraint(
        "uq_job_sources_identity",
        "job_sources",
        ["source", "source_key", "external_id", "occurrence"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_job_sources_identity", "job_sources", type_="unique")
    op.create_unique_constraint(
        op.f("uq_job_sources_identity"),
        "job_sources",
        ["source", "external_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("job_sources", "active")
    op.drop_column("job_sources", "missing_since")
    op.drop_column("job_sources", "missing_snapshot_count")
    op.drop_column("job_sources", "occurrence")
    op.drop_column("job_sources", "source_key")
    # ### end Alembic commands ###
