"""add notification outbox

Revision ID: 75a32a50e2cb
Revises: a74afb2f1286
Create Date: 2026-07-13 20:21:20.361276
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "75a32a50e2cb"
down_revision: str | Sequence[str] | None = "a74afb2f1286"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telegram_link_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_telegram_link_tokens_hash", "telegram_link_tokens", ["token_hash"], unique=True
    )
    op.add_column(
        "notification_deliveries",
        sa.Column(
            "cadence",
            sa.Enum(
                "instant",
                "hourly",
                "daily",
                name="delivery_cadence",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "notification_deliveries", sa.Column("recipient", sa.String(length=320), nullable=True)
    )
    op.add_column(
        "notification_deliveries",
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "notification_deliveries",
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "notification_deliveries", sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.execute(
        "UPDATE notification_deliveries SET cadence = 'instant', recipient = '', "
        "idempotency_key = match_id::text || ':' || channel"
    )
    op.alter_column("notification_deliveries", "cadence", nullable=False)
    op.alter_column("notification_deliveries", "recipient", nullable=False)
    op.alter_column("notification_deliveries", "idempotency_key", nullable=False)
    op.create_unique_constraint(
        "uq_delivery_idempotency_key", "notification_deliveries", ["idempotency_key"]
    )
    op.add_column(
        "profiles",
        sa.Column(
            "email_notifications_enabled",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    op.add_column(
        "profiles",
        sa.Column(
            "telegram_notifications_enabled",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profiles", "telegram_notifications_enabled")
    op.drop_column("profiles", "email_notifications_enabled")
    op.drop_constraint("uq_delivery_idempotency_key", "notification_deliveries", type_="unique")
    op.drop_column("notification_deliveries", "locked_at")
    op.drop_column("notification_deliveries", "last_attempt_at")
    op.drop_column("notification_deliveries", "idempotency_key")
    op.drop_column("notification_deliveries", "recipient")
    op.drop_column("notification_deliveries", "cadence")
    op.drop_index("ix_telegram_link_tokens_hash", table_name="telegram_link_tokens")
    op.drop_table("telegram_link_tokens")
    # ### end Alembic commands ###
