export const ROLE_OPTIONS = [
  "Software Engineering",
  "Software Developer",
  "SWE",
  "SDE",
  "Backend Engineering",
  "Frontend Engineering",
  "Full Stack Engineering",
  "Mobile Engineering",
  "iOS Engineering",
  "Android Engineering",
  "Data Science",
  "Data Analytics",
  "Data Engineering",
  "Machine Learning",
  "Artificial Intelligence",
  "Cloud Engineering",
  "DevOps",
  "Site Reliability Engineering",
  "Infrastructure Engineering",
  "Cybersecurity",
  "Quality Assurance",
  "Test Engineering",
  "Embedded Systems",
  "Firmware Engineering",
  "Hardware Engineering",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Robotics",
  "Product Management",
  "Program Management",
  "Project Management",
  "UX Design",
  "UI Design",
  "Business Analysis",
  "Consulting",
  "Quantitative Research",
  "Finance",
  "Marketing",
  "Sales",
  "Operations",
] as const;

export const LOCATION_OPTIONS = [
  "Remote",
  "Canada",
  "United States",
  "Toronto, ON",
  "Vancouver, BC",
  "Montreal, QC",
  "Ottawa, ON",
  "Waterloo, ON",
  "Kitchener, ON",
  "Calgary, AB",
  "Edmonton, AB",
  "Halifax, NS",
  "Victoria, BC",
  "Winnipeg, MB",
  "Saskatoon, SK",
  "Quebec City, QC",
  "New York, NY",
  "San Francisco, CA",
  "Seattle, WA",
  "Boston, MA",
  "Austin, TX",
  "Chicago, IL",
  "Los Angeles, CA",
  "Washington, DC",
  "United Kingdom",
  "London, UK",
] as const;
